[package]
name = "hotlib"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3"
derive_more = "0.15"
failure = "0.1.5"
humantime = "1.3"
libloading = "0.5"
notify = "5.0.0-pre.1"
serde_json = "1"
slug = "0.1"
